baseurl = "https://www.oranlooney.com/"
title = "OranLooney.com"
theme = "whiteplain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en"
paginate = 100

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright {year} Oran Looney"

[outputs]
	home = ["HTML","RSS","JSON"]

# This is displayer in About page.
[params.author]
  name = "Oran Looney"

  # Gravatar or Abatar image
  gravatar = "4fd33509c8963cefcdb6bf03af9c34cc"
  github = "olooney"
  linkedin = "oran-looney"
  # twitter = "oranlooney"
  stackoverflow = "273231/olooney"
  crossvalidated = "48250/olooney"
  tumblr = "honeycode"
  # email = "olooney@gmail.com"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Search"
  url = "/search/"
[[menu.main]]
  name = "Tags"
  weight = 2
  url = "/tags/"
[[menu.main]]
  name = "Archives"
  weight = 3
  url = "/archives/"
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Quotes"
  identifier = "quotes"
  url = "/quotes/"

